In [1]:
import pandas as pd
import numpy as np

In [3]:
demographic = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/dataset1/Demographics/demographics.csv")

In [2]:
sensing = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/dataset1/Sensing/sensing_cleaned.csv")

C:\Users\Acer\AppData\Local\Temp\ipykernel_5296\1018143358.py:1: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  sensing = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/dataset1/Sensing/sensing_cleaned.csv")

In [3]:
sensing.nunique()

uid                            216
day                           1721
loc_home_unlock_duration    130290
loc_home_unlock_num         108349
sleep_duration                 137
sleep_end                      129
sleep_start                    130
act_in_vehicle_ep_avg        13876
act_in_vehicle_hr_avg        13876
act_on_bike_ep_avg            3946
act_on_bike_hr_avg            3946
act_running_ep_avg            2895
act_running_hr_avg            2895
act_still_ep_avg             32209
act_still_hr_avg             52520
act_unknown_hr_avg            8634
act_walking_ep_avg           25683
act_walking_hr_avg           25683
unlock_duration_ep_avg      136870
unlock_duration_hr_avg      136997
unlock_num_ep_avg              560
unlock_num_hr_avg              569
dtype: int64

In [4]:
sensing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137481 entries, 0 to 137480
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   uid                       137481 non-null  object
 1   day                       137481 non-null  int64
 2   loc_home_unlock_duration  137481 non-null  object
 3   loc_home_unlock_num       137481 non-null  object
 4   sleep_duration            137481 non-null  object
 5   sleep_end                 137481 non-null  int64
 6   sleep_start               137481 non-null  int64
 7   act_in_vehicle_ep_avg     137481 non-null  float64
 8   act_in_vehicle_hr_avg     137481 non-null  object
 9   act_on_bike_ep_avg        137481 non-null  float64
 10  act_on_bike_hr_avg        137481 non-null  object
 11  act_running_ep_avg        137481 non-null  float64
 12  act_running_hr_avg        137481 non-null  object
 13  act_still_ep_avg          137481 non-null  float64
 14  act_still_hr_avg          137481 non-null  object
 15  act_unknown_hr_avg        137481 non-null  object
 16  act_walking_ep_avg        137481 non-null  float64
 17  act_walking_hr_avg        137481 non-null  object
 18  unlock_duration_ep_avg    137481 non-null  object
 19  unlock_duration_hr_avg    137481 non-null  object
 20  unlock_num_ep_avg         137481 non-null  float64
 21  unlock_num_hr_avg         137481 non-null  object
dtypes: float64(6), int64(3), object(13)
memory usage: 23.1+ MB

In [5]:
sensing.duplicated().sum()

np.int64(0)

In [8]:
demographic = demographic.drop(labels='race',axis=1)

In [9]:
demographic.head()

                                uid gender
0  3569e2f520db9014b4acc4227a6421c1   both
1  ac70fe1f8115ac361f2023269c011c3e      M
2  3bb377ba0acb7d8916010184df36aa57      F
3  fa394f6d3d077bd5568fc3bc01580806      F
4  84120765740b5395aa49a2feb12fbb43      M

In [11]:
demographic['gender'].unique()

array(['both', 'M', 'F'], dtype=object)

In [13]:
demographic['gender'] = demographic['gender'].replace('both', 'F')

In [15]:
demographic.to_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/dataset1/Demographics/demographics1.csv", index=False)

In [16]:
ge = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/dataset1/EMA/general_ema.csv")

In [ ]:
ge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217155 entries, 0 to 217154
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   uid                 217155 non-null  object
 1   day                 217155 non-null  int64
 2   pam                 35186 non-null   float64
 3   phq4-1              35348 non-null   float64
 4   phq4-2              35348 non-null   float64
 5   phq4-3              35348 non-null   float64
 6   phq4-4              35348 non-null   float64
 7   phq4_resp_mean      35348 non-null   float64
 8   phq4_resp_median    35348 non-null   float64
 9   phq4_score          35348 non-null   float64
 10  social_level        35348 non-null   float64
 11  sse3-1              35348 non-null   float64
 12  sse3-2              35348 non-null   float64
 13  sse3-3              35348 non-null   float64
 14  sse3-4              35348 non-null   float64
 15  sse3_resp_mean      35348 non-null   float64
 16  sse3_resp_median    35348 non-null   float64
 17  stress              35348 non-null   float64
 18  avg_ema_spent_time  39007 non-null   float64
dtypes: float64(17), int64(1), object(1)
memory usage: 31.5+ MB

In [18]:
ge.isnull().sum()

uid                        0
day                        0
pam                   181969
phq4-1                181807
phq4-2                181807
phq4-3                181807
phq4-4                181807
phq4_resp_mean        181807
phq4_resp_median      181807
phq4_score            181807
social_level          181807
sse3-1                181807
sse3-2                181807
sse3-3                181807
sse3-4                181807
sse3_resp_mean        181807
sse3_resp_median      181807
stress                181807
avg_ema_spent_time    178148
dtype: int64

In [ ]:
ge = ge.drop(labels='day',axis=1)
ge = ge.drop(labels='pam',axis=1)
ge = ge.drop(labels='avg_ema_spent_time',axis=1)

In [27]:
ge.isnull().sum()

uid                      0
phq4-1              181807
phq4-2              181807
phq4-3              181807
phq4-4              181807
phq4_resp_mean      181807
phq4_resp_median    181807
phq4_score          181807
social_level        181807
sse3-1              181807
sse3-2              181807
sse3-3              181807
sse3-4              181807
sse3_resp_mean      181807
sse3_resp_median    181807
stress              181807
dtype: int64

In [28]:
ge.dropna(inplace=True)

In [29]:
ge.isnull().sum()

uid                 0
phq4-1              0
phq4-2              0
phq4-3              0
phq4-4              0
phq4_resp_mean      0
phq4_resp_median    0
phq4_score          0
social_level        0
sse3-1              0
sse3-2              0
sse3-3              0
sse3-4              0
sse3_resp_mean      0
sse3_resp_median    0
stress              0
dtype: int64

In [31]:
ge.count()

uid                 35348
phq4-1              35348
phq4-2              35348
phq4-3              35348
phq4-4              35348
phq4_resp_mean      35348
phq4_resp_median    35348
phq4_score          35348
social_level        35348
sse3-1              35348
sse3-2              35348
sse3-3              35348
sse3-4              35348
sse3_resp_mean      35348
sse3_resp_median    35348
stress              35348
dtype: int64

- uid (ID người dùng duy nhất): Mã định danh duy nhất của người dùng.
- pam (Chỉ số PAM - Photographic Affect Meter): Điểm đo cảm xúc bằng hình ảnh. Người dùng chọn một hình từ 16 hình ảnh. Giá trị từ 1 đến 16.
- phq4-1 (Câu hỏi PHQ4-1): Trong 2 tuần qua, bạn có thường xuyên cảm thấy lo lắng, căng thẳng hoặc bồn chồn không?
- phq4-2 (Câu hỏi PHQ4-2): Trong 2 tuần qua, bạn có thường xuyên cảm thấy không thể dừng hoặc kiểm soát việc lo lắng không?
- phq4-3 (Câu hỏi PHQ4-3): Trong 2 tuần qua, bạn có thường xuyên cảm thấy chán nản, tuyệt vọng hoặc buồn bã không?
- phq4-4 (Câu hỏi PHQ4-4): Trong 2 tuần qua, bạn có thường xuyên cảm thấy ít hứng thú hoặc niềm vui trong các hoạt động không?
- phq4_resp_mean (Thời gian trung bình trả lời PHQ4): Thời gian trung bình người dùng trả lời các câu hỏi PHQ4 (tính bằng giây).
- phq4_resp_median (Thời gian trung vị trả lời PHQ4): Thời gian trung vị người dùng trả lời các câu hỏi PHQ4 (tính bằng giây).
- phq4_score (Tổng điểm PHQ4): Tổng điểm PHQ4 (tổng của PHQ4-1 đến PHQ4-4).
- social_level (Mức độ giao tiếp xã hội): Trong ngày hôm nay, bạn dành nhiều thời gian ở một mình hay với người khác?
- sse3-1 (Thang đo lòng tự trọng - Câu 1): Hiện tại, tôi lo lắng về việc người khác nghĩ gì về tôi.
- sse3-2 (Thang đo lòng tự trọng - Câu 2): Hiện tại, tôi hài lòng với ngoại hình của mình.
- sse3-3 (Thang đo lòng tự trọng - Câu 3): Hiện tại, tôi cảm thấy mình thông minh như những người khác.
- sse3-4 (Thang đo lòng tự trọng - Câu 4): Nhìn chung, hiện tại tôi cảm thấy tốt về bản thân mình.
- sse3_resp_mean (Thời gian trung bình trả lời thang tự trọng): Thời gian trung bình trả lời các câu hỏi về lòng tự trọng (tính bằng giây).
- sse3_resp_median (Thời gian trung vị trả lời thang tự trọng): Thời gian trung vị trả lời các câu hỏi về lòng tự trọng (tính bằng giây).
- stress (Mức độ căng thẳng hiện tại): Bạn có đang cảm thấy căng thẳng ngay bây giờ không?
- avg_ema_spent_time (Thời gian trung bình hoàn thành EMA): Thời gian trung bình người dùng dành để hoàn thành bảng EMA (tính bằng giây).

In [3]:
step = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/dataset1/Sensing/steps.csv")

In [4]:
step.describe()

,day,step_ep_0,step_ep_1,step_ep_2,step_ep_3,step_hr_0,step_hr_1,step_hr_2,step_hr_3,step_hr_4,...,step_hr_14,step_hr_15,step_hr_16,step_hr_17,step_hr_18,step_hr_19,step_hr_20,step_hr_21,step_hr_22,step_hr_23
count,1.764580e+05,176458.000000,176458.000000,176458.000000,176458.000000,176458.000000,176458.000000,176458.000000,176458.000000,176458.000000,...,176458.000000,176458.000000,176458.000000,176458.000000,176458.000000,176458.000000,176458.000000,176458.000000,176458.000000,176458.000000
mean,2.019513e+07,6714.978374,752.668771,3976.509691,1985.799913,148.748286,86.370354,40.163314,20.891589,16.495965,...,464.419465,462.784595,472.491375,468.991930,483.201045,416.034614,336.986818,285.233965,241.852724,222.490746
std,1.189160e+04,5292.956220,1646.319317,3703.539892,2352.560180,545.659991,390.397279,283.953773,217.565298,170.647323,...,903.963763,977.072945,941.392680,914.414226,838.858400,843.052354,696.444616,726.508866,675.160489,814.353529
min,2.017091e+07,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.019013e+07,2803.000000,3.000000,1347.000000,353.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.019112e+07,5966.000000,130.000000,3331.000000,1327.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,129.000000,108.000000,114.000000,131.000000,159.000000,115.000000,69.000000,45.000000,21.000000,0.000000
75%,2.020102e+07,9344.000000,920.000000,5550.000000,2905.000000,38.000000,0.000000,0.000000,0.000000,0.000000,...,628.000000,610.000000,622.000000,652.000000,723.000000,582.000000,398.000000,290.000000,199.000000,117.000000
max,2.022061e+07,166763.000000,78064.000000,166456.000000,82914.000000,70724.000000,55562.000000,35907.000000,31634.000000,15311.000000,...,65562.000000,165466.000000,70925.000000,68915.000000,67131.000000,80534.000000,69722.000000,73737.000000,64535.000000,51816.000000

In [5]:
step.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176458 entries, 0 to 176457
Data columns (total 30 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   uid         176458 non-null  object
 1   day         176458 non-null  int64
 2   step_ep_0   176458 non-null  int64
 3   step_ep_1   176458 non-null  int64
 4   step_ep_2   176458 non-null  int64
 5   step_ep_3   176458 non-null  int64
 6   step_hr_0   176458 non-null  int64
 7   step_hr_1   176458 non-null  int64
 8   step_hr_2   176458 non-null  int64
 9   step_hr_3   176458 non-null  int64
 10  step_hr_4   176458 non-null  int64
 11  step_hr_5   176458 non-null  int64
 12  step_hr_6   176458 non-null  int64
 13  step_hr_7   176458 non-null  int64
 14  step_hr_8   176458 non-null  int64
 15  step_hr_9   176458 non-null  int64
 16  step_hr_10  176458 non-null  int64
 17  step_hr_11  176458 non-null  int64
 18  step_hr_12  176458 non-null  int64
 19  step_hr_13  176458 non-null  int64
 20  step_hr_14  176458 non-null  int64
 21  step_hr_15  176458 non-null  int64
 22  step_hr_16  176458 non-null  int64
 23  step_hr_17  176458 non-null  int64
 24  step_hr_18  176458 non-null  int64
 25  step_hr_19  176458 non-null  int64
 26  step_hr_20  176458 non-null  int64
 27  step_hr_21  176458 non-null  int64
 28  step_hr_22  176458 non-null  int64
 29  step_hr_23  176458 non-null  int64
dtypes: int64(29), object(1)
memory usage: 40.4+ MB

In [7]:
sensing['day'] = pd.to_datetime(sensing['day'], format='%Y%m%d')

In [8]:
sensing.head()

,uid,day,loc_home_unlock_duration,loc_home_unlock_num,sleep_duration,sleep_end,sleep_start,act_in_vehicle_ep_avg,act_in_vehicle_hr_avg,act_on_bike_ep_avg,...,act_running_hr_avg,act_still_ep_avg,act_still_hr_avg,act_unknown_hr_avg,act_walking_ep_avg,act_walking_hr_avg,unlock_duration_ep_avg,unlock_duration_hr_avg,unlock_num_ep_avg,unlock_num_hr_avg
0,1ff6d7f34acb354430e7323a35ff7703,2017-09-11,5.01224937505,2.29073555034,9.25,94,20,0.000000,0.0,0.0,...,0.20833333333333334,26576.666667,3322.083333,0.0,2221.333333,277.6666666666667,2150.269,268.78362500000003,23.000000,2.9166666666666665
1,1ff6d7f34acb354430e7323a35ff7703,2017-09-12,3.02514298684,2.99591466182,9.5,94,18,0.000000,0.0,0.0,...,0.0,26167.333333,3270.916667,0.0,2632.333333,329.0416666666667,1312.5406666666668,164.06758333333332,19.333333,2.5
2,1ff6d7f34acb354430e7323a35ff7703,2017-09-13,2.20231269844,1.70505376533,8.75,92,22,0.000000,0.0,0.0,...,0.0,25944.666667,3243.083333,0.0,2855.000000,"356,875",2129.8006666666665,266.2250833333333,17.000000,"2,125"
3,1ff6d7f34acb354430e7323a35ff7703,2017-09-14,2.03633634204,2.4513064133,8.75,94,24,83.666667,10.458333333333334,0.0,...,0.20833333333333334,26545.333333,3318.166667,0.0,2169.000000,"271,125",784.5390000000001,98.06737499999998,22.666667,2.8333333333333335
4,1ff6d7f34acb354430e7323a35ff7703,2017-09-15,7.95750124688,5.68578553616,11.25,96,6,0.000000,0.0,0.0,...,1.8333333333333333,26183.000000,3272.875,0.0,2602.000000,325.25,1384.4063333333334,173.0507916666667,24.333333,3.0833333333333335

In [75]:
print(type(ge1['day'].iloc[0]))

<class 'str'>

In [84]:
ge = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/EMA/general_ema.csv")
step = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/step.csv")
demographic = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Demographics/demographics.csv")

In [85]:
ge.info()
step.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35348 entries, 0 to 35347
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   uid                 35348 non-null  object
 1   day                 35348 non-null  object
 2   phq4_1              35348 non-null  float64
 3   phq4_2              35348 non-null  float64
 4   phq4_3              35348 non-null  float64
 5   phq4_4              35348 non-null  float64
 6   phq4_resp_mean      35348 non-null  float64
 7   phq4_resp_median    35348 non-null  float64
 8   phq4_score          35348 non-null  float64
 9   social_level        35348 non-null  float64
 10  sse3_1              35348 non-null  float64
 11  sse3_2              35348 non-null  float64
 12  sse3_3              35348 non-null  float64
 13  sse3_4              35348 non-null  float64
 14  sse3_resp_mean      35348 non-null  float64
 15  sse3_resp_median    35348 non-null  float64
 16  stress              35348 non-null  float64
 17  avg_ema_spent_time  35348 non-null  float64
dtypes: float64(16), object(2)
memory usage: 4.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176458 entries, 0 to 176457
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   uid          176458 non-null  object
 1   day          176458 non-null  object
 2   steps_total  176458 non-null  int64
dtypes: int64(1), object(2)
memory usage: 4.0+ MB

In [86]:
demographic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   uid     216 non-null    object
 1   gender  216 non-null    object
dtypes: object(2)
memory usage: 3.5+ KB

In [87]:
ge.duplicated().sum()
demographic.duplicated().sum()
step.duplicated().sum()

np.int64(0)

In [95]:
import pandas as pd

# 1️⃣ Đọc file dữ liệu
ge = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/EMA/general_ema.csv")

# 2️⃣ Lọc các bản ghi có thời gian trả lời trung bình (avg_ema_spent_time) > 30 giây
ge = ge[ge['avg_ema_spent_time'] > 25]

# 3️⃣ Tạo cột mới 'sse3_score' = tổng điểm của 4 câu hỏi tự tôn
# (giả sử các cột tên là: sse3-1, sse3-2, sse3-3, sse3-4)
ge['sse3_score'] = ge[['sse3_1', 'sse3_2', 'sse3_3', 'sse3_4']].sum(axis=1)

# 4️⃣ (Tuỳ chọn) Kiểm tra nhanh dữ liệu sau khi xử lý
print(ge[['avg_ema_spent_time', 'sse3_1', 'sse3_2', 'sse3_3', 'sse3_4', 'sse3_score']].head())

# 5️⃣ (Tuỳ chọn) Xuất ra file mới nếu bạn muốn lưu kết quả
ge.to_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/EMA/general_ema_filtered.csv", index=False)

print("✅ Đã lọc dữ liệu >30s và thêm cột 'sse3_score' thành công!")

   avg_ema_spent_time  sse3_1  sse3_2  sse3_3  sse3_4  sse3_score
0           37.385698       1       3       3       3          10
1           52.117245       2       3       3       3          11
2         1351.983871       1       2       2       3           8
3           87.877848       1       3       3       3          10
4           26.443065       1       2       2       2           7
✅ Đã lọc dữ liệu >30s và thêm cột 'sse3_score' thành công!

In [96]:
import pandas as pd
from datetime import datetime, timedelta

# Giả sử bạn đã có dataframe ge
# (với các cột: sleep_duration, sleep_start, sleep_end)
sensing = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/sensing.csv")
def convert_to_time(epoch_value):
    """Chuyển đổi epoch (mỗi đơn vị = 7.5 phút kể từ 8PM) sang dạng HH:MM"""
    # Mốc bắt đầu: 8PM hôm trước
    base_time = datetime.strptime("20:00", "%H:%M")
    # Cộng thêm (epoch_value * 7.5 phút)
    new_time = base_time + timedelta(minutes=epoch_value * 7.5)
    # Nếu vượt qua 24h thì quay về mốc giờ trong ngày
    new_time = new_time - timedelta(days=new_time.day - base_time.day)
    return new_time.strftime("%H:%M")

# Tạo hai cột mới cho thời gian thực tế
sensing["sleep_start_time"] = sensing["sleep_start"].apply(convert_to_time)
sensing["sleep_end_time"] = sensing["sleep_end"].apply(convert_to_time)

# Kiểm tra kết quả
print(sensing[["sleep_start", "sleep_start_time", "sleep_end", "sleep_end_time", "sleep_duration"]].head())

   sleep_start sleep_start_time  sleep_end sleep_end_time  sleep_duration
0           26            23:15         88          07:00            7.75
1           20            22:30         72          05:00            6.50
2           24            23:00         88          07:00            8.00
3           32            00:00         78          05:45            5.75
4           38            00:45         86          06:45            6.00

In [97]:
sensing.to_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/sensing1.csv", index=False)

In [2]:
sensing = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/sensing1.csv")

In [3]:
sensing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16715 entries, 0 to 16714
Data columns (total 29 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   uid                           16715 non-null  object
 1   day                           16715 non-null  object
 2   sleep_duration                16715 non-null  float64
 3   sleep_start                   16715 non-null  int64
 4   sleep_start_time              16715 non-null  object
 5   sleep_end                     16715 non-null  int64
 6   sleep_end_time                16715 non-null  object
 7   loc_home_unlock_duration_avg  16715 non-null  float64
 8   loc_home_unlock_num           16715 non-null  float64
 9   loc_home_dur                  16715 non-null  float64
 10  loc_leisure_dur               16715 non-null  float64
 11  loc_social_dur                16715 non-null  float64
 12  loc_study_dur                 16715 non-null  float64
 13  loc_workout_dur               16715 non-null  float64
 14  loc_worship_dur               16715 non-null  float64
 15  act_in_vehicle_ep_avg         16715 non-null  float64
 16  act_on_foot_ep_avg            16715 non-null  float64
 17  act_running_ep_avg            16715 non-null  int64
 18  act_still_ep_avg              16715 non-null  float64
 19  act_walking_ep_avg            16715 non-null  int64
 20  audio_amp_mean_ep_avg         16715 non-null  float64
 21  audio_amp_std_ep_avg          16715 non-null  float64
 22  audio_convo_duration_ep_avg   16715 non-null  float64
 23  audio_convo_num_ep_avg        16715 non-null  float64
 24  audio_voice_ep_avg            16715 non-null  float64
 25  loc_dist_ep_avg               16715 non-null  float64
 26  loc_visit_num_ep_avg          16715 non-null  float64
 27  unlock_duration_ep_avg        16715 non-null  float64
 28  unlock_num_ep_avg             16715 non-null  float64
dtypes: float64(21), int64(4), object(4)
memory usage: 3.7+ MB

In [5]:
sensing.isnull().sum()
sensing.duplicated().sum()

np.int64(0)

In [19]:
cols_to_convert = [
    'act_in_vehicle_ep_avg',
    'act_on_foot_ep_avg',
    'act_running_ep_avg',
    'act_still_ep_avg',
    'act_walking_ep_avg',
    'Unlock_duration_ep_avg'
]

# Kiểm tra cột nào tồn tại trong DataFrame để tránh lỗi
existing_cols = [col for col in cols_to_convert if col in sensing.columns]

# Chuyển đổi từ giây sang giờ (1 giờ = 3600 giây)
sensing[existing_cols] = sensing[existing_cols] / 3600

# Lưu lại file mới nếu muốn
sensing.to_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/sensing2.csv", index=False)

print("Đã chuyển đổi thành công các cột từ giây sang giờ!")

Đã chuyển đổi thành công các cột từ giây sang giờ!

In [20]:
sensing = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/sensing2.csv")

In [22]:
sensing.loc[:,["act_in_vehicle_ep_avg","act_on_foot_ep_avg"]]

       act_in_vehicle_ep_avg  act_on_foot_ep_avg
0               8.307613e-05            0.416852
1               7.237654e-05            0.700370
2               2.361111e-05            0.463148
3               9.176955e-05            0.458426
4               4.714506e-05            0.268519
...                      ...                 ...
16710           1.028807e-06            0.267407
16711           1.208848e-06            0.436759
16712           5.915638e-07            0.618889
16713           3.284722e-04            0.290463
16714           1.622942e-05            0.023426

[16715 rows x 2 columns]

In [11]:
import pandas as pd
sensing = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/sensing2.csv")

In [12]:
sensing['act_in_vehicle_ep_avg'].head()

0    1076.666667
1     938.000000
2     306.000000
3    1189.333333
4     611.000000
Name: act_in_vehicle_ep_avg, dtype: float64

In [15]:
sensing['act_in_vehicle_ep_avg'] = sensing['act_in_vehicle_ep_avg'] / 3600
sensing['act_in_vehicle_ep_avg'] = sensing['act_in_vehicle_ep_avg'].map(lambda x: format(x, '.6f'))

In [16]:
sensing['act_in_vehicle_ep_avg'].head()

0    0.299074
1    0.260556
2    0.085000
3    0.330370
4    0.169722
Name: act_in_vehicle_ep_avg, dtype: object

In [17]:
sensing.to_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/sensing3.csv", index=False)

In [34]:
import pandas as pd

# === 1. Đọc file demographic (chứa uid và uid_new) ===
demo = pd.read_csv(
    "D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Demographics/demographics.csv",
    dtype={'uid': str, 'uid_new': str}
)

# Chuẩn hóa UID (bỏ khoảng trắng, chữ thường)
demo['uid'] = demo['uid'].str.strip().str.lower()

# Tạo dict map: uid cũ → uid_new
uid_map = demo.set_index('uid')['uid_new'].to_dict()

# === 2. Đọc các file dữ liệu chính (đảm bảo uid đọc dạng chuỗi) ===
ge = pd.read_csv(
    "D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/EMA/general_ema.csv",
    dtype={'uid': str}
)
step = pd.read_csv(
    "D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/step.csv",
    dtype={'uid': str}
)
sensing = pd.read_csv(
    "D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/sensing.csv",
    dtype={'uid': str}
)

# Chuẩn hóa UID trong các file này
for df in [ge, step, sensing]:
    df['uid'] = df['uid'].astype(str).str.strip().str.lower()

# === 3. Map UID mới dựa vào dict ===
for name, df in [('general_ema', ge), ('step', step), ('sensing', sensing)]:
    df['uid_new'] = df['uid'].map(uid_map)
    print(f"{name}: {df['uid_new'].notna().sum()} mapped / {len(df)} total")

    # Nếu không map được thì giữ nguyên UID cũ
    df['uid'] = df['uid_new'].fillna(df['uid'])
    df.drop(columns=['uid_new'], inplace=True)

# === 4. Xuất lại file kết quả ===
ge.to_csv(
    "D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/EMA/general_ema_mapped.csv",
    index=False
)
step.to_csv(
    "D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/step_mapped.csv",
    index=False
)
sensing.to_csv(
    "D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/sensing_mapped.csv",
    index=False
)

print("✅ Đã mapping UID mới (HSxxx) cho cả 3 file thành công và giữ nguyên UID cũ nếu không khớp!")

general_ema: 11155 mapped / 11318 total
step: 175503 mapped / 176458 total
sensing: 16715 mapped / 16715 total
✅ Đã mapping UID mới (HSxxx) cho cả 3 file thành công và giữ nguyên UID cũ nếu không khớp!

In [35]:
ge_unmapped = ge.loc[~ge['uid'].isin(demo['uid_new'])]
print(ge_unmapped['uid'].unique()[:10])

['ea716dd032aaa0dcf8bfa36b1811917f' '8617ddac1f48b148e3683738519b2e7a']

In [36]:
ge.nunique()

uid              217
day             1669
phq4_1             4
phq4_2             4
phq4_3             4
phq4_4             4
phq4_score        13
social_level       5
sse3_1             5
sse3_2             5
sse3_3             5
sse3_4             5
sse3_score        17
stress             5
dtype: int64

In [37]:
sensing.nunique()

uid                                34
day                              1677
sleep_duration                    135
sleep_start                       127
sleep_start_time                  127
sleep_end                         128
sleep_end_time                    128
loc_home_unlock_duration_avg    16625
loc_home_unlock_num             16623
loc_home_dur                    16664
loc_leisure_dur                  1010
loc_social_dur                   2589
loc_study_dur                    6777
loc_workout_dur                  1018
loc_worship_dur                   228
act_in_vehicle_ep_avg            4042
act_on_foot_ep_avg               6806
act_still_ep_avg                12958
audio_amp_mean_ep_avg           16473
audio_amp_std_ep_avg            16473
audio_convo_duration_ep_avg     13143
audio_convo_num_ep_avg             86
audio_voice_ep_avg              16397
loc_dist_ep_avg                 14958
loc_visit_num_ep_avg               33
unlock_duration_ep_avg          16672
unlock_num_ep_avg                 457
dtype: int64

In [38]:
import pandas as pd

# === 1. Đọc lại 3 file đã mapping ===
ge = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/EMA/general_ema_mapped.csv")
step = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/step_mapped.csv")
sensing = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/sensing_mapped.csv")

# === 2. Chỉ giữ lại UID mới (bắt đầu bằng 'HS') ===
ge = ge[ge['uid'].astype(str).str.startswith('HS')]
step = step[step['uid'].astype(str).str.startswith('HS')]
sensing = sensing[sensing['uid'].astype(str).str.startswith('HS')]

# === 3. Xuất lại file mới sạch UID cũ ===
ge.to_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/output/general_ema_clean.csv", index=False)
step.to_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/output/step_clean.csv", index=False)
sensing.to_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/output/sensing_clean.csv", index=False)

print("✅ Đã xóa toàn bộ các dòng có UID cũ, chỉ giữ lại UID mới (HSxxx) trong cả 3 file!")

✅ Đã xóa toàn bộ các dòng có UID cũ, chỉ giữ lại UID mới (HSxxx) trong cả 3 file!

In [2]:
import pandas as pd

# === 1. Đọc lại 3 file sạch ===
ge = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/EMA/general_ema.csv")
step = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/step.csv")
sensing = pd.read_csv("D:/UTH/kho dữ liệu và hệ thống hỗ trợ ra quyết định/project/data/main data/Sensing/sensing.csv")

# === 2. Chuẩn hoá kiểu dữ liệu cột day (nếu cần) ===
for df in [ge, step, sensing]:
    if 'day' in df.columns:
        df['day'] = pd.to_datetime(df['day'], errors='coerce').dt.date

# === 3. Giữ lại các cột cần thiết ===
ge = ge[['uid', 'day']].dropna(subset=['uid', 'day']).drop_duplicates()
step = step[['uid', 'day']].dropna(subset=['uid', 'day']).drop_duplicates()
sensing = sensing[['uid', 'day']].dropna(subset=['uid', 'day']).drop_duplicates()

# === 4. Tìm giao nhau giữa ba bảng theo cả uid và day ===
common_uid_day = ge.merge(step, on=['uid', 'day'], how='inner').merge(sensing, on=['uid', 'day'], how='inner')

# === 5. In kết quả tổng hợp ===
print("🟢 Tổng số dòng (uid, day) trong general_ema:", len(ge))
print("🟢 Tổng số dòng (uid, day) trong step:", len(step))
print("🟢 Tổng số dòng (uid, day) trong sensing:", len(sensing))
print("-------------------------------------------------")
print("✅ Số dòng (uid, day) xuất hiện trong cả 3 file:", len(common_uid_day))

🟢 Tổng số dòng (uid, day) trong general_ema: 11155
🟢 Tổng số dòng (uid, day) trong step: 175503
🟢 Tổng số dòng (uid, day) trong sensing: 172797
-------------------------------------------------
✅ Số dòng (uid, day) xuất hiện trong cả 3 file: 8809